/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'tr';

type LanguageProviderProps = {
  children: React.ReactNode;
  defaultLanguage?: Language;
  storageKey?: string;
};

type LanguageProviderState = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Page Header
    "Welcome back": "Welcome back",
    "Welcome back, {name}": "Welcome back, {name}",
    "Here's your Daily Dashboard Overview.": "Here's your Daily Dashboard Overview.",
    
    // Sidebar Groups
    "Main": "Main",
    "Game": "Game",
    "Drivers": "Drivers",
    "Human Resources Department": "Human Resources Department",
    "Event Department": "Event Department",
    "Admin": "Admin",

    // Sidebar items
    "Dashboard": "Dashboard",
    "Banner": "Banner",
    "Members": "Members",
    "Download": "Download",
    "Map": "Map",
    "Jobs": "Jobs",
    "Events": "Events",
    "Ranking": "Ranking",
    "FAQ": "FAQ",
    "LOA Requests": "LOA Requests",
    "LOA Management": "LOA Management",
    "Attendance Logs": "Attendance Logs",
    "Blacklist Driver": "Blacklist Driver",
    "Driver Manage": "Driver Manage",
    "Left Drivers": "Left Drivers",
    "HR Applications": "HR Applications",
    "Event Calendar Manage": "Event Calendar Manage",
    "Event invites": "Event invites",
    "Blacklist VTC's": "Blacklist VTC's",
    "All members": "All members",
    "Blacklist Staff/Management": "Blacklist Staff/Management",
    "History": "History",
    "Support": "Support",
    "Settings": "Settings",
    "Account settings": "Account settings",
    "Sign out": "Sign out",

    // Stat Cards
    "Drivers Number": "Drivers Number",
    "Total VTC Members": "Total VTC Members",
    "Total Jobs": "Total Jobs",
    "All-time completed deliveries": "All-time completed deliveries",
    "Total Distance": "Total Distance",
    "Distance on completed jobs": "Distance on completed jobs",
    "Events This Month": "Events This Month",
    "VTC Events Attending": "VTC Events Attending",

    // Job Statistics Card
    "Job Statistics": "Job Statistics",
    "Performance overview of distance and deliveries.": "Performance overview of distance and deliveries.",
    "View performance": "View performance",

    // Upcoming Convoy Card
    "No upcoming convoys": "No upcoming convoys",
    "View info": "View info",
    "To be determined": "To be determined",
    "Euro Truck Simulator 2": "Euro Truck Simulator 2",
    "American Truck Simulator": "American Truck Simulator",

    // Dashboard Table
    "Detail informations of jobs": "Detail informations of jobs",
    "Latest deliveries logged in Trucky.": "Latest deliveries logged in Trucky.",
    "Driver": "Driver",
    "Route": "Route",
    "Cargo": "Cargo",
    "Distance": "Distance",
    "No recent jobs found.": "No recent jobs found.",
    "Showing": "Showing",
    "to": "to",
    "of": "of",
    "entries": "entries",
    "Previous": "Previous",
    "Next": "Next",
    "Showing {start} to {end} of {total} entries": "Showing {start} to {end} of {total} entries",

    // Ranking Page
    "Driver rankings": "Driver rankings",
    "Each job is counted once. Distance is the sum of km on completed jobs only (not the same as counting all job rows or cancelled runs). Cancelled or unfinished jobs are excluded.": "Each job is counted once. Distance is the sum of km on completed jobs only (not the same as counting all job rows or cancelled runs). Cancelled or unfinished jobs are excluded.",
    "Could not load job data for rankings.": "Could not load job data for rankings.",
    "Top driver (jobs)": "Top driver (jobs)",
    "completed deliveries": "completed deliveries",
    "Top driver (distance)": "Top driver (distance)",
    "km on completed jobs": "km on completed jobs",
    "Period jobs": "Period jobs",
    "Completed deliveries (all time)": "Completed deliveries (all time)",
    "completed only": "completed only",
    "Period distance": "Period distance",
    "Distance on completed jobs (period)": "Distance on completed jobs (period)",
    "Leaderboard": "Leaderboard",
    "Top 50 drivers by completed jobs or distance. Month filter applies instantly — each job counted once (duplicates from the API are removed).": "Top 50 drivers by completed jobs or distance. Month filter applies instantly — each job counted once (duplicates from the API are removed).",
    "All Time": "All Time",
    "No job data for this period.": "No job data for this period.",

    // Events Page
    "Upcoming events": "Upcoming events",
    "Attending convoys from TruckersMP (VTC: Eternal Transport).": "Attending convoys from TruckersMP (VTC: Eternal Transport).",
    "Today": "Today",
    "Selected day": "Selected day",
    "No events on this day.": "No events on this day.",
    "Next attending convoys": "Next attending convoys",
    "Total listed:": "Total listed:",
    "Loading…": "Loading…",
    "No upcoming events found.": "No upcoming events found.",
    "Failed to load events": "Failed to load events",
    "event(s)": "event(s)",

    // Jobs Page
    "No job data loaded.": "No job data loaded.",
    "No jobs found in the logs.": "No jobs found in the logs.",
    "Could not load jobs from Trucky. Try again later.": "Could not load jobs from Trucky. Try again later.",

    // FAQ Page
    "Quick answers for drivers — bans, staff, convoy equipment, and in-game help.": "Quick answers for drivers — bans, staff, convoy equipment, and in-game help.",
    "What should I do if I get banned in TMP?": "What should I do if I get banned in TMP?",
    "Contact HR via direct message as soon as possible. They will guide you on next steps.": "Contact HR via direct message as soon as possible. They will guide you on next steps.",
    "Not reporting a ban may lead to warnings or removal from the VTC.": "Not reporting a ban may lead to warnings or removal from the VTC.",
    "How can I apply for staff?": "How can I apply for staff?",
    "You can apply using the": "You can apply using the",
    "Google Form": "Google Form",
    ". Leadership may also share the link elsewhere.": ". Leadership may also share the link elsewhere.",
    "You should receive a response within 24–72 hours.": "You should receive a response within 24–72 hours.",
    "Which truck and trailer are we using?": "Which truck and trailer are we using?",
    "Check the #konvoy-bilgi channel on Discord. Required truck and trailer details for each convoy are posted there.": "Check the #konvoy-bilgi channel on Discord. Required truck and trailer details for each convoy are posted there.",
    "Why is the convoy moving so slowly?": "Why is the convoy moving so slowly?",
    "Convoy Control may reduce speed to close gaps between drivers. That keeps the convoy organised and reduces the chance of people taking wrong turns or splitting the pack.": "Convoy Control may reduce speed to close gaps between drivers. That keeps the convoy organised and reduces the chance of people taking wrong turns or splitting the pack.",
    "Issue in game?": "Issue in game?",
    "Tell higher ranks (e.g. in Discord). They can point you to the right person or fix where possible.": "Tell higher ranks (e.g. in Discord). They can point you to the right person or fix where possible.",

    // Settings Page & Roles
    "Authentication Required": "Authentication Required",
    "Please log in to access your settings.": "Please log in to access your settings.",
    "Log In / Create Test User": "Log In / Create Test User",
    "Profile Information": "Profile Information",
    "Profile Banner": "Profile Banner",
    "Upload an image or enter a banner URL.": "Upload an image or enter a banner URL.",
    "Update Banner": "Update Banner",
    "Username": "Username",
    "Edit": "Edit",
    "Profile Settings": "Profile Settings",
    "Display Name / Username": "Display Name / Username",
    "Enter custom username": "Enter custom username",
    "This name will be shown on the dashboard and your menu.": "This name will be shown on the dashboard and your menu.",
    "Update Username": "Update Username",
    "Cancel": "Cancel",
    "Delete": "Delete",
    "Connected Accounts": "Connected Accounts",
    "Discord": "Discord",
    "Connected as {username}": "Connected as {username}",
    "Sign into EThub using your Discord account": "Sign into EThub using your Discord account",
    "Disconnect": "Disconnect",
    "Connect Discord": "Connect Discord",
    "Steam": "Steam",
    "Sign into EThub using your Steam account": "Sign into EThub using your Steam account",
    "Connect Steam": "Connect Steam",
    "Trucky ID": "Trucky ID",
    "Enter your Trucky ID for accurate job tracking": "Enter your Trucky ID for accurate job tracking",
    "Add": "Add",
    "Your Trucky ID": "Your Trucky ID",
    "Enter your Trucky driver ID": "Enter your Trucky driver ID",
    "Enter your Trucky ID to accurately match your jobs from the Trucky API. This ensures your profile shows only your actual completed jobs.": "Enter your Trucky ID to accurately match your jobs from the Trucky API. This ensures your profile shows only your actual completed jobs.",
    "Save": "Save",
    "Update Avatar": "Update Avatar",
    "Use Discord Avatar": "Use Discord Avatar",
    "Use Steam Avatar": "Use Steam Avatar",
    "Fetching...": "Fetching...",
    "Avatar URL": "Avatar URL",
    "Enter avatar image URL": "Enter avatar image URL",
    "Pick an avatar source: Discord, Steam, upload a file, or enter an image URL.": "Pick an avatar source: Discord, Steam, upload a file, or enter an image URL.",
    "Updating...": "Updating...",
    "Banner URL": "Banner URL",
    "Enter banner image URL": "Enter banner image URL",
    "Upload Banner Image": "Upload Banner Image",
    "Upload a custom profile banner or point to an image URL. The selected banner will appear on your profile page.": "Upload a custom profile banner or point to an image URL. The selected banner will appear on your profile page.",
    "Save Banner": "Save Banner",
    "Manage your profile, connections, and preferences.": "Manage your profile, connections, and preferences.",
    "HR Staff": "HR Staff",
    "HR Manager": "HR Manager",
    "Event Staff": "Event Staff",
    "Event Manager": "Event Manager",
    "Member": "Member",

    // New pages keys
    "Unknown": "Unknown",
    "All Members": "All Members",
    "Add User": "Add User",
    "Join Requests": "Join Requests",
    "Search by name, Discord ID, Steam ID…": "Search by name, Discord ID, Steam ID…",
    "All Roles": "All Roles",
    "Clear": "Clear",
    "No members found": "No members found",
    "No users created yet. Click \"Add User\" to get started.": "No users created yet. Click \"Add User\" to get started.",
    "No users match your current filters.": "No users match your current filters.",
    "Rank": "Rank",
    "Last Login": "Last Login",
    "Member Since": "Member Since",
    "Profile": "Profile",
    "View": "View",
    "No pending requests": "No pending requests",
    "When someone signs in via Discord and is not yet registered, their join request will appear here.": "When someone signs in via Discord and is not yet registered, their join request will appear here.",
    "Applicant": "Applicant",
    "Discord ID": "Discord ID",
    "Discord Username": "Discord Username",
    "Requested": "Requested",
    "Actions": "Actions",
    "Accept": "Accept",
    "Decline": "Decline",
    "Add New User": "Add New User",
    "Display Name": "Display Name",
    "e.g. John Smith": "e.g. John Smith",
    "Required so this user can log in via Discord.": "Required so this user can log in via Discord.",
    "Department is automatically assigned based on rank.": "Department is automatically assigned based on rank.",
    "Edit User": "Edit User",
    "Save Changes": "Save Changes",
    "Accept Join Request": "Accept Join Request",
    "No Discord ID": "No Discord ID",
    "Assign Rank": "Assign Rank",
    "Approve": "Approve",
    "Click me": "Click me",
    "Active now": "Active now",
    "Pending": "Pending",
    "Are you sure you want to remove this user?": "Are you sure you want to remove this user?",
    "Are you sure you want to decline and remove this join request?": "Are you sure you want to decline and remove this join request?",
    "Downloads Center": "Downloads Center",
    "Access VTC resources, client saves, skin mods, and profile configurations.": "Access VTC resources, client saves, skin mods, and profile configurations.",
    "Search files by name or category…": "Search files by name or category…",
    "All Categories": "All Categories",
    "Resources": "Resources",
    "Mods": "Mods",
    "Documents": "Documents",
    "Others": "Others",
    "No files found": "No files found",
    "No files have been uploaded to the registry yet.": "No files have been uploaded to the registry yet.",
    "No files match your search criteria.": "No files match your search criteria.",
    "Uploaded by:": "Uploaded by:",
    "Upload Registry File": "Upload Registry File",
    "Add rule books, telemetry profiles, client saves or skins.": "Add rule books, telemetry profiles, client saves or skins.",
    "Select File": "Select File",
    "Click to select file": "Click to select file",
    "Download Title": "Download Title",
    "Category": "Category",
    "Upload & Sync File": "Upload & Sync File",
    "About Downloads": "About Downloads",
    "This downloads catalog is synchronized automatically across your active browser sessions.": "This downloads catalog is synchronized automatically across your active browser sessions.",
    "Drivers and staff can download any file from the panel on the left, but only VTC Administrators are authorized to upload or delete assets.": "Drivers and staff can download any file from the panel on the left, but only VTC Administrators are authorized to upload or delete assets.",
    "Are you sure?": "Are you sure?",
    "Are you sure you want to delete \"{name}\"? This action cannot be undone.": "Are you sure you want to delete \"{name}\"? This action cannot be undone.",
    "Large File": "Large File",
    "Files larger than ~4.5 MB may not persist due to browser storage limits.": "Files larger than ~4.5 MB may not persist due to browser storage limits.",
    "Upload Failed": "Upload Failed",
    "Could not read the selected file. Please try a different file.": "Could not read the selected file. Please try a different file.",
    "File size exceeds the 10MB limit. Please upload a smaller file.": "File size exceeds the 10MB limit. Please upload a smaller file.",
    "File could not be saved due to browser storage limits.": "File could not be saved due to browser storage limits.",
    "File Uploaded": "File Uploaded",
    "File Deleted": "File Deleted",
    "Search events...": "Search events...",
    "Convoy": "Convoy",
    "All Day": "All Day",
    "+{count} more": "+{count} more",
    "Mon": "Mon",
    "Tue": "Tue",
    "Wed": "Wed",
    "Thu": "Thu",
    "Fri": "Fri",
    "Sat": "Sat",
    "Sun": "Sun",
    "LOA requests": "LOA requests",
    "Submit a leave of absence. HR reviews it on": "Submit a leave of absence. HR reviews it on",
    "New request": "New request",
    "Please fill in start date, end date, and a reason.": "Please fill in start date, end date, and a reason.",
    "End date must be on or after the start date.": "End date must be on or after the start date.",
    "Request sent to LOA Management for approval.": "Request sent to LOA Management for approval.",
    "Date of start": "Date of start",
    "Date of end": "Date of end",
    "Reasons": "Reasons",
    "Explain why you need leave…": "Explain why you need leave…",
    "Submit to LOA Management": "Submit to LOA Management",
    "Your LOA history": "Your LOA history",
    "No requests yet.": "No requests yet.",
    "Submitted": "Submitted",
    "Reviewed": "Reviewed",
    "LOA management": "LOA management",
    "Approve or reject driver leave requests. New submissions appear here from": "Approve or reject driver leave requests. New submissions appear here from",
    "Pending ({count})": "Pending ({count})",
    "No pending requests.": "No pending requests.",
    "Reject": "Reject",
    "Dates": "Dates",
    "No approved or rejected requests yet.": "No approved or rejected requests yet.",
    "Decided": "Decided",
  },
  tr: {
    // Page Header
    "Welcome back": "Tekrar hoş geldin",
    "Welcome back, {name}": "Tekrar hoş geldin, {name}",
    "Here's your Daily Dashboard Overview.": "İşte Günlük Kontrol Paneli Özetiniz.",
    
    // Sidebar Groups
    "Main": "Ana Sayfa",
    "Game": "Oyun",
    "Drivers": "Sürücüler",
    "Human Resources Department": "İnsan Kaynakları Departmanı",
    "Event Department": "Etkinlik Departmanı",
    "Admin": "Yönetici",

    // Sidebar items
    "Dashboard": "Kontrol Paneli",
    "Banner": "Afiş",
    "Members": "Üyeler",
    "Download": "İndir",
    "Map": "Harita",
    "Jobs": "İşler",
    "Events": "Etkinlikler",
    "Ranking": "Sıralama",
    "FAQ": "SSS",
    "LOA Requests": "İzin İstekleri",
    "LOA Management": "İzin Yönetimi",
    "Attendance Logs": "Katılım Kayıtları",
    "Blacklist Driver": "Kara Listedeki Sürücüler",
    "Driver Manage": "Sürücü Yönetimi",
    "Left Drivers": "Ayrılan Sürücüler",
    "HR Applications": "İK Başvuruları",
    "Event Calendar Manage": "Etkinlik Takvimi Yönetimi",
    "Event invites": "Etkinlik Davetleri",
    "Blacklist VTC's": "Kara Listedeki VTC'ler",
    "All members": "Tüm Üyeler",
    "Blacklist Staff/Management": "Kara Listedeki Yetkililer",
    "History": "Geçmiş",
    "Support": "Destek",
    "Settings": "Ayarlar",
    "Account settings": "Hesap Ayarları",
    "Sign out": "Oturumu Kapat",

    // Stat Cards
    "Drivers Number": "Sürücü Sayısı",
    "Total VTC Members": "Toplam VTC Üyesi",
    "Total Jobs": "Toplam İş",
    "All-time completed deliveries": "Tüm zamanların tamamlanan teslimatları",
    "Total Distance": "Toplam Mesafe",
    "Distance on completed jobs": "Tamamlanan işlerdeki mesafe",
    "Events This Month": "Bu Ayki Etkinlikler",
    "VTC Events Attending": "Katılınan VTC Etkinlikleri",

    // Job Statistics Card
    "Job Statistics": "İş İstatistikleri",
    "Performance overview of distance and deliveries.": "Mesafe ve teslimatların performans genel bakışı.",
    "View performance": "Performansı görüntüle",

    // Upcoming Convoy Card
    "No upcoming convoys": "Yaklaşan konvoy yok",
    "View info": "Bilgiyi görüntüle",
    "To be determined": "Belirlenecek",
    "Euro Truck Simulator 2": "Euro Truck Simulator 2",
    "American Truck Simulator": "American Truck Simulator",

    // Dashboard Table
    "Detail informations of jobs": "İşlerin detaylı bilgileri",
    "Latest deliveries logged in Trucky.": "Trucky'de kaydedilen son teslimatlar.",
    "Driver": "Sürücü",
    "Route": "Rota",
    "Cargo": "Kargo",
    "Distance": "Mesafe",
    "No recent jobs found.": "Son bulunan iş yok.",
    "Showing": "Gösteriliyor",
    "to": "ile",
    "of": "toplam",
    "entries": "giriş arasından",
    "Previous": "Önceki",
    "Next": "Sonraki",
    "Showing {start} to {end} of {total} entries": "{total} giriş arasından {start} ile {end} arası gösteriliyor",

    // Ranking Page
    "Driver rankings": "Sürücü Sıralaması",
    "Each job is counted once. Distance is the sum of km on completed jobs only (not the same as counting all job rows or cancelled runs). Cancelled or unfinished jobs are excluded.": "Her iş bir kez sayılır. Mesafe yalnızca tamamlanan işlerdeki km'lerin toplamıdır (iptal edilen veya yarım bırakılan işler dahil değildir).",
    "Could not load job data for rankings.": "Sıralama için iş verileri yüklenemedi.",
    "Top driver (jobs)": "En iyi sürücü (iş)",
    "completed deliveries": "tamamlanan teslimat",
    "Top driver (distance)": "En iyi sürücü (mesafe)",
    "km on completed jobs": "km tamamlanan işlerde",
    "Period jobs": "Dönem işleri",
    "Completed deliveries (all time)": "Tamamlanan teslimatlar (tüm zamanlar)",
    "completed only": "yalnızca tamamlananlar",
    "Period distance": "Dönem mesafesi",
    "Distance on completed jobs (period)": "Tamamlanan işlerdeki mesafe (dönem)",
    "Leaderboard": "Liderlik Tablosu",
    "Top 50 drivers by completed jobs or distance. Month filter applies instantly — each job counted once (duplicates from the API are removed).": "Tamamlanan iş veya mesafeye göre ilk 50 sürücü. Ay filtresi anında uygulanır — her iş bir kez sayılır.",
    "All Time": "Tüm Zamanlar",
    "No job data for this period.": "Bu dönem için iş verisi yok.",

    // Events Page
    "Upcoming events": "Yaklaşan etkinlikler",
    "Attending convoys from TruckersMP (VTC: Eternal Transport).": "TruckersMP'den katılınan konvoylar (VTC: Eternal Transport).",
    "Today": "Bugün",
    "Selected day": "Seçilen gün",
    "No events on this day.": "Bu günde etkinlik yok.",
    "Next attending convoys": "Sonraki katılınan konvoylar",
    "Total listed:": "Toplam listelenen:",
    "Loading…": "Yükleniyor…",
    "No upcoming events found.": "Yaklaşan etkinlik bulunamadı.",
    "Failed to load events": "Etkinlikler yüklenemedi",
    "event(s)": "etkinlik",

    // Jobs Page
    "No job data loaded.": "İş verisi yüklenemedi.",
    "No jobs found in the logs.": "Kayıtlarda iş bulunamadı.",
    "Could not load jobs from Trucky. Try again later.": "Trucky'den işler yüklenemedi. Daha sonra tekrar deneyin.",

    // FAQ Page
    "Quick answers for drivers — bans, staff, convoy equipment, and in-game help.": "Sürücüler için hızlı yanıtlar — yasaklar, personel, konvoy ekipmanı ve oyun içi yardım.",
    "What should I do if I get banned in TMP?": "TMP'de yasaklanırsam ne yapmalıyım?",
    "Contact HR via direct message as soon as possible. They will guide you on next steps.": "En kısa sürede İK ile doğrudan mesaj aracılığıyla iletişime geçin. Sonraki adımlar için size rehberlik edeceklerdir.",
    "Not reporting a ban may lead to warnings or removal from the VTC.": "Yasağı bildirmemek uyarılara veya VTC'den çıkarılmaya yol açabilir.",
    "How can I apply for staff?": "Personel başvurusu nasıl yapabilirim?",
    "You can apply using the": "Başvurmak için",
    "Google Form": "Google Formu",
    ". Leadership may also share the link elsewhere.": "kullanabilirsiniz. Liderlik bağlantıyı başka yerlerde de paylaşabilir.",
    "You should receive a response within 24–72 hours.": "24–72 saat içinde yanıt almalısınız.",
    "Which truck and trailer are we using?": "Hangi kamyon ve treyler kullanılıyor?",
    "Check the #konvoy-bilgi channel on Discord. Required truck and trailer details for each convoy are posted there.": "Discord'daki #konvoy-bilgi kanalını kontrol edin. Her konvoy için gereken kamyon ve treyler bilgileri orada paylaşılır.",
    "Why is the convoy moving so slowly?": "Konvoy neden bu kadar yavaş ilerliyor?",
    "Convoy Control may reduce speed to close gaps between drivers. That keeps the convoy organised and reduces the chance of people taking wrong turns or splitting the pack.": "Konvoy Kontrolü, sürücüler arasındaki boşlukları kapatmak için hızı düşürebilir. Bu, konvoyu düzenli tutar ve yanlış dönüş alma veya grubu bölme olasılığını azaltır.",
    "Issue in game?": "Oyun içi sorun mu?",
    "Tell higher ranks (e.g. in Discord). They can point you to the right person or fix where possible.": "Üst rütbelere bildirin (örn. Discord'da). Sizi doğru kişiye yönlendirebilir veya mümkün olan durumlarda sorunu çözebilirler.",

    // Settings Page & Roles
    "Authentication Required": "Kimlik Doğrulaması Gerekli",
    "Please log in to access your settings.": "Ayarlarınıza erişmek için lütfen giriş yapın.",
    "Log In / Create Test User": "Giriş Yap / Test Kullanıcısı Oluştur",
    "Profile Information": "Profil Bilgileri",
    "Profile Banner": "Profil Afişi",
    "Upload an image or enter a banner URL.": "Bir resim yükleyin veya bir afiş URL'si girin.",
    "Update Banner": "Afişi Güncelle",
    "Username": "Kullanıcı Adı",
    "Edit": "Düzenle",
    "Profile Settings": "Profil Ayarları",
    "Display Name / Username": "Görünen Ad / Kullanıcı Adı",
    "Enter custom username": "Özel kullanıcı adı girin",
    "This name will be shown on the dashboard and your menu.": "Bu ad kontrol panelinde ve menünüzde gösterilecektir.",
    "Update Username": "Kullanıcı Adını Güncelle",
    "Cancel": "İptal",
    "Delete": "Sil",
    "Connected Accounts": "Bağlı Hesaplar",
    "Discord": "Discord",
    "Connected as {username}": "{username} olarak bağlandı",
    "Sign into EThub using your Discord account": "Discord hesabınızı kullanarak EThub'a giriş yapın",
    "Disconnect": "Bağlantıyı Kes",
    "Connect Discord": "Discord'u Bağla",
    "Steam": "Steam",
    "Sign into EThub using your Steam account": "Steam hesabınızı kullanarak EThub'a giriş yapın",
    "Connect Steam": "Steam'i Bağla",
    "Trucky ID": "Trucky ID",
    "Enter your Trucky ID for accurate job tracking": "Doğru iş takibi için Trucky ID'nizi girin",
    "Add": "Ekle",
    "Your Trucky ID": "Trucky ID'niz",
    "Enter your Trucky driver ID": "Trucky sürücü ID'nizi girin",
    "Enter your Trucky ID to accurately match your jobs from the Trucky API. This ensures your profile shows only your actual completed jobs.": "İşlerinizi Trucky API'sinden doğru bir şekilde eşleştirmek için Trucky ID'nizi girin. Bu, profilinizin yalnızca gerçek tamamlanmış işlerinizi göstermesini sağlar.",
    "Save": "Kaydet",
    "Update Avatar": "Avatarı Güncelle",
    "Use Discord Avatar": "Discord Avatarını Kullan",
    "Use Steam Avatar": "Steam Avatarını Kullan",
    "Fetching...": "Alınıyor...",
    "Avatar URL": "Avatar URL'si",
    "Enter avatar image URL": "Avatar resim URL'si girin",
    "Pick an avatar source: Discord, Steam, upload a file, or enter an image URL.": "Bir avatar kaynağı seçin: Discord, Steam, dosya yükleyin veya resim URL'si girin.",
    "Updating...": "Güncelleniyor...",
    "Banner URL": "Afiş URL'si",
    "Enter banner image URL": "Afiş resim URL'si girin",
    "Upload Banner Image": "Afiş Resmi Yükle",
    "Upload a custom profile banner or point to an image URL. The selected banner will appear on your profile page.": "Özel bir profil afişi yükleyin veya bir resim URL'si belirtin. Seçilen afiş profil sayfanızda görünecektir.",
    "Save Banner": "Afişi Kaydet",
    "Manage your profile, connections, and preferences.": "Profilinizi, bağlantılarınızı ve tercihlerinizi yönetin.",
    "HR Staff": "İK Personeli",
    "HR Manager": "İK Yöneticisi",
    "Event Staff": "Etkinlik Personeli",
    "Event Manager": "Etkinlik Yöneticisi",
    "Member": "Üye",

    // New pages keys
    "Unknown": "Bilinmeyen",
    "All Members": "Tüm Üyeler",
    "Add User": "Kullanıcı Ekle",
    "Join Requests": "Katılım İstekleri",
    "Search by name, Discord ID, Steam ID…": "İsim, Discord ID, Steam ID ile ara…",
    "All Roles": "Tüm Roller",
    "Clear": "Temizle",
    "No members found": "Üye bulunamadı",
    "No users created yet. Click \"Add User\" to get started.": "Henüz kullanıcı oluşturulmadı. Başlamak için \"Kullanıcı Ekle\"ye tıklayın.",
    "No users match your current filters.": "Mevcut filtrelerinizle eşleşen kullanıcı yok.",
    "Rank": "Rütbe",
    "Last Login": "Son Giriş",
    "Member Since": "Üyelik Tarihi",
    "Profile": "Profil",
    "View": "Görüntüle",
    "No pending requests": "Bekleyen istek yok",
    "When someone signs in via Discord and is not yet registered, their join request will appear here.": "Birisi Discord üzerinden giriş yaptığında ve henüz kayıtlı olmadığında, katılım isteği burada görünecektir.",
    "Applicant": "Başvuran",
    "Discord ID": "Discord ID",
    "Discord Username": "Discord Kullanıcı Adı",
    "Requested": "Talep Edildi",
    "Actions": "Eylemler",
    "Accept": "Kabul Et",
    "Decline": "Reddet",
    "Add New User": "Yeni Kullanıcı Ekle",
    "Display Name": "Görünen Ad",
    "e.g. John Smith": "Örn. John Smith",
    "Required so this user can log in via Discord.": "Bu kullanıcının Discord üzerinden giriş yapabilmesi için gereklidir.",
    "Department is automatically assigned based on rank.": "Departman, rütbeye göre otomatik olarak atanır.",
    "Edit User": "Kullanıcıyı Düzenle",
    "Save Changes": "Değişiklikleri Kaydet",
    "Accept Join Request": "Katılım İsteğini Kabul Et",
    "No Discord ID": "Discord ID Yok",
    "Assign Rank": "Rütbe Ata",
    "Approve": "Onayla",
    "Click me": "Bana tıkla",
    "Active now": "Şu an aktif",
    "Pending": "Beklemede",
    "Are you sure you want to remove this user?": "Bu kullanıcıyı kaldırmak istediğinizden emin misiniz?",
    "Are you sure you want to decline and remove this join request?": "Bu katılım isteğini reddedip kaldırmak istediğinizden emin misiniz?",
    "Downloads Center": "İndirme Merkezi",
    "Access VTC resources, client saves, skin mods, and profile configurations.": "VTC kaynaklarına, istemci kayıtlarına, kaplama modlarına ve profil yapılandırmalarına erişin.",
    "Search files by name or category…": "Dosyaları isim veya kategoriye göre ara…",
    "All Categories": "Tüm Kategoriler",
    "Resources": "Kaynaklar",
    "Mods": "Modlar",
    "Documents": "Belgeler",
    "Others": "Diğerleri",
    "No files found": "Dosya bulunamadı",
    "No files have been uploaded to the registry yet.": "Henüz arşive hiçbir dosya yüklenmedi.",
    "No files match your search criteria.": "Arama kriterlerinize uygun dosya bulunamadı.",
    "Uploaded by:": "Yükleyen:",
    "Upload Registry File": "Kayıt Dosyası Yükle",
    "Add rule books, telemetry profiles, client saves or skins.": "Kural kitapları, telemetri profilleri, istemci kayıtları veya kaplamalar ekleyin.",
    "Select File": "Dosya Seç",
    "Click to select file": "Dosya seçmek için tıklayın",
    "Download Title": "İndirme Başlığı",
    "Category": "Kategori",
    "Upload & Sync File": "Dosyayı Yükle ve Eşitle",
    "About Downloads": "İndirmeler Hakkında",
    "This downloads catalog is synchronized automatically across your active browser sessions.": "Bu indirme kataloğu, aktif tarayıcı oturumlarınız arasında otomatik olarak eşitlenir.",
    "Drivers and staff can download any file from the panel on the left, but only VTC Administrators are authorized to upload or delete assets.": "Sürücüler ve personel soldaki panelden herhangi bir dosyayı indirebilir, ancak yalnızca VTC Yöneticileri varlık yüklemeye veya silmeye yetkilidir.",
    "Are you sure?": "Emin misiniz?",
    "Are you sure you want to delete \"{name}\"? This action cannot be undone.": "\"{name}\" dosyasını silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    "Large File": "Büyük Dosya",
    "Files larger than ~4.5 MB may not persist due to browser storage limits.": "~4.5 MB'tan büyük dosyalar tarayıcı depolama limitleri nedeniyle kalıcı olmayabilir.",
    "Upload Failed": "Yükleme Başarısız",
    "Could not read the selected file. Please try a different file.": "Seçilen dosya okunamadı. Lütfen farklı bir dosya deneyin.",
    "File size exceeds the 10MB limit. Please upload a smaller file.": "Dosya boyutu 10MB sınırını aşıyor. Lütfen daha küçük bir dosya yükleyin.",
    "File could not be saved due to browser storage limits.": "Tarayıcı depolama limitleri nedeniyle dosya kaydedilemedi.",
    "File Uploaded": "Dosya Yükledi",
    "File Deleted": "Dosya Silindi",
    "Search events...": "Etkinlikleri ara...",
    "Convoy": "Konvoy",
    "All Day": "Tüm Gün",
    "+{count} more": "+{count} daha",
    "Mon": "Pzt",
    "Tue": "Sal",
    "Wed": "Çar",
    "Thu": "Per",
    "Fri": "Cum",
    "Sat": "Cmt",
    "Sun": "Paz",
    "LOA requests": "İzin istekleri",
    "Submit a leave of absence. HR reviews it on": "İzin talebi gönderin. İK bunu şurada inceler:",
    "New request": "Yeni talep",
    "Please fill in start date, end date, and a reason.": "Lütfen başlangıç tarihini, bitiş tarihini ve bir neden girin.",
    "End date must be on or after the start date.": "Bitiş tarihi, başlangıç tarihinden önce olamaz.",
    "Request sent to LOA Management for approval.": "Talep onay için İzin Yönetimine gönderildi.",
    "Date of start": "Başlangıç Tarihi",
    "Date of end": "Bitiş Tarihi",
    "Reasons": "Nedenler",
    "Explain why you need leave…": "Neden izne ihtiyacınız olduğunu açıklayın…",
    "Submit to LOA Management": "İzin Yönetimine Gönder",
    "Your LOA history": "İzin geçmişiniz",
    "No requests yet.": "Henüz talep yok.",
    "Submitted": "Gönderildi",
    "Reviewed": "İncelendi",
    "LOA management": "İzin yönetimi",
    "Approve or reject driver leave requests. New submissions appear here from": "Sürücü izin taleplerini onaylayın veya reddedin. Yeni gönderimler şuradan burada görünür:",
    "Pending ({count})": "Bekleyen ({count})",
    "No pending requests.": "Bekleyen talep yok.",
    "Reject": "Reddet",
    "Dates": "Tarihler",
    "No approved or rejected requests yet.": "Henüz onaylanmış veya reddedilmiş talep yok.",
    "Decided": "Karar Verildi",
  }
};

const LanguageContext = createContext<LanguageProviderState | undefined>(undefined);

export function LanguageProvider({
  children,
  defaultLanguage = 'en',
  storageKey = 'ethub-language',
}: LanguageProviderProps) {
  const [language, setLangState] = useState<Language>(
    () => (localStorage.getItem(storageKey) as Language) || defaultLanguage
  );

  const setLanguage = (lang: Language) => {
    localStorage.setItem(storageKey, lang);
    setLangState(lang);
  };

  const t = (key: string, replacements?: Record<string, string | number>): string => {
    const langDict = translations[language] || translations.en;
    let translation = langDict[key] || key;

    if (replacements) {
      Object.entries(replacements).forEach(([placeholder, value]) => {
        translation = translation.replace(`{${placeholder}}`, String(value));
      });
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
